import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './components/footer/Footer'
import Navbar from './components/navbar/Navbar'
import CartProvider from '@/provider/CartProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Burada.com',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
           <div className='flex flex-col min-h-screen'>
            <Navbar/> 
              <main className='flex-grow'>{children}</main>
              <Footer/> 
            </div>
          </CartProvider>
          
      </body>
    </html>
  )
}
